// <auto-generated />
using System;
using DataHandler.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataHandler.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20231121204542_Users")]
    partial class Users
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("DataHandler.DataAccess.Customer", b =>
                {
                    b.Property<int>("CusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("CusName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.HasKey("CusCode");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CusCode = 324195,
                            Address = "ΣΩΡΟΥ 1 ΜΕΤΑΜΟΡΦΩΣΗ",
                            CusName = "XXXXXXX XXXXXXX",
                            Phone = "9999999999",
                            PostalCode = "14451"
                        },
                        new
                        {
                            CusCode = 509989,
                            Address = "ΣΩΡΟΥ 1 ΜΕΤΑΜΟΡΦΩΣΗ",
                            CusName = "XXXXXXX XXXXXXX",
                            Phone = "9999999999",
                            PostalCode = "14451"
                        },
                        new
                        {
                            CusCode = 687355,
                            Address = "ΣΩΡΟΥ 1 ΜΕΤΑΜΟΡΦΩΣΗ",
                            CusName = "XXXXXXX XXXXXXX",
                            Phone = "9999999999",
                            PostalCode = "14451"
                        },
                        new
                        {
                            CusCode = 884663,
                            Address = "ΣΩΡΟΥ 1 ΜΕΤΑΜΟΡΦΩΣΗ",
                            CusName = "XXXXXXX XXXXXXX",
                            Phone = "9999999999",
                            PostalCode = "14451"
                        },
                        new
                        {
                            CusCode = 893623,
                            Address = "ΣΩΡΟΥ 1 ΜΕΤΑΜΟΡΦΩΣΗ",
                            CusName = "XXXXXXX XXXXXXX",
                            Phone = "9999999999",
                            PostalCode = "14451"
                        });
                });

            modelBuilder.Entity("DataHandler.DataAccess.CustomerInvoice", b =>
                {
                    b.Property<string>("InvoiceNo")
                        .HasColumnType("TEXT");

                    b.Property<int>("CusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalValue")
                        .HasColumnType("REAL");

                    b.HasKey("InvoiceNo");

                    b.HasIndex("CusCode");

                    b.ToTable("CustomerInvoices");

                    b.HasData(
                        new
                        {
                            InvoiceNo = "000574",
                            CusCode = 324195,
                            IssueDate = new DateTime(2022, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 538.67999999999995
                        },
                        new
                        {
                            InvoiceNo = "000577",
                            CusCode = 324195,
                            IssueDate = new DateTime(2022, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 3437.1500000000001
                        },
                        new
                        {
                            InvoiceNo = "000578",
                            CusCode = 324195,
                            IssueDate = new DateTime(2022, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 2471.1599999999999
                        },
                        new
                        {
                            InvoiceNo = "000586",
                            CusCode = 324195,
                            IssueDate = new DateTime(2022, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 3370.5100000000002
                        },
                        new
                        {
                            InvoiceNo = "000553",
                            CusCode = 509989,
                            IssueDate = new DateTime(2022, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 6631.9499999999998
                        },
                        new
                        {
                            InvoiceNo = "000568",
                            CusCode = 509989,
                            IssueDate = new DateTime(2022, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 8280.7299999999996
                        },
                        new
                        {
                            InvoiceNo = "000569",
                            CusCode = 509989,
                            IssueDate = new DateTime(2022, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 2788.4699999999998
                        },
                        new
                        {
                            InvoiceNo = "000584",
                            CusCode = 509989,
                            IssueDate = new DateTime(2022, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 1810.3399999999999
                        },
                        new
                        {
                            InvoiceNo = "000542",
                            CusCode = 687355,
                            IssueDate = new DateTime(2022, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 454.08999999999997
                        },
                        new
                        {
                            InvoiceNo = "000547",
                            CusCode = 687355,
                            IssueDate = new DateTime(2022, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 4164.2299999999996
                        },
                        new
                        {
                            InvoiceNo = "000548",
                            CusCode = 687355,
                            IssueDate = new DateTime(2022, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 4097.9499999999998
                        },
                        new
                        {
                            InvoiceNo = "000549",
                            CusCode = 687355,
                            IssueDate = new DateTime(2022, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 7149.4700000000003
                        },
                        new
                        {
                            InvoiceNo = "000550",
                            CusCode = 687355,
                            IssueDate = new DateTime(2022, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 5091.2399999999998
                        },
                        new
                        {
                            InvoiceNo = "000543",
                            CusCode = 884663,
                            IssueDate = new DateTime(2022, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 7423.3800000000001
                        },
                        new
                        {
                            InvoiceNo = "000561",
                            CusCode = 884663,
                            IssueDate = new DateTime(2022, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 864.52999999999997
                        },
                        new
                        {
                            InvoiceNo = "000564",
                            CusCode = 884663,
                            IssueDate = new DateTime(2022, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 1194.24
                        },
                        new
                        {
                            InvoiceNo = "000565",
                            CusCode = 884663,
                            IssueDate = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 4451.1400000000003
                        },
                        new
                        {
                            InvoiceNo = "000566",
                            CusCode = 884663,
                            IssueDate = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 4973.5100000000002
                        },
                        new
                        {
                            InvoiceNo = "000571",
                            CusCode = 884663,
                            IssueDate = new DateTime(2022, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 1506.1800000000001
                        },
                        new
                        {
                            InvoiceNo = "000572",
                            CusCode = 884663,
                            IssueDate = new DateTime(2022, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 6642.1700000000001
                        },
                        new
                        {
                            InvoiceNo = "000575",
                            CusCode = 884663,
                            IssueDate = new DateTime(2022, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 3749.29
                        },
                        new
                        {
                            InvoiceNo = "000576",
                            CusCode = 884663,
                            IssueDate = new DateTime(2022, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 1175.3800000000001
                        },
                        new
                        {
                            InvoiceNo = "000582",
                            CusCode = 884663,
                            IssueDate = new DateTime(2022, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 8325.2199999999993
                        },
                        new
                        {
                            InvoiceNo = "000583",
                            CusCode = 884663,
                            IssueDate = new DateTime(2022, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 9903.9200000000001
                        },
                        new
                        {
                            InvoiceNo = "000585",
                            CusCode = 884663,
                            IssueDate = new DateTime(2022, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 4530.1499999999996
                        },
                        new
                        {
                            InvoiceNo = "000587",
                            CusCode = 884663,
                            IssueDate = new DateTime(2022, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 9161.3400000000001
                        },
                        new
                        {
                            InvoiceNo = "000588",
                            CusCode = 884663,
                            IssueDate = new DateTime(2022, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 542.69000000000005
                        },
                        new
                        {
                            InvoiceNo = "000593",
                            CusCode = 884663,
                            IssueDate = new DateTime(2022, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 1478.4100000000001
                        },
                        new
                        {
                            InvoiceNo = "000544",
                            CusCode = 893623,
                            IssueDate = new DateTime(2022, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 1310.8599999999999
                        },
                        new
                        {
                            InvoiceNo = "000545",
                            CusCode = 893623,
                            IssueDate = new DateTime(2022, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 7162.2299999999996
                        },
                        new
                        {
                            InvoiceNo = "000546",
                            CusCode = 893623,
                            IssueDate = new DateTime(2022, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 571.63999999999999
                        },
                        new
                        {
                            InvoiceNo = "000555",
                            CusCode = 893623,
                            IssueDate = new DateTime(2022, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 2950.7600000000002
                        },
                        new
                        {
                            InvoiceNo = "000556",
                            CusCode = 893623,
                            IssueDate = new DateTime(2022, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 8889.7999999999993
                        },
                        new
                        {
                            InvoiceNo = "000557",
                            CusCode = 893623,
                            IssueDate = new DateTime(2022, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 1903.26
                        },
                        new
                        {
                            InvoiceNo = "000579",
                            CusCode = 893623,
                            IssueDate = new DateTime(2022, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 3180.8200000000002
                        },
                        new
                        {
                            InvoiceNo = "000589",
                            CusCode = 893623,
                            IssueDate = new DateTime(2022, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 2131.1199999999999
                        },
                        new
                        {
                            InvoiceNo = "000590",
                            CusCode = 893623,
                            IssueDate = new DateTime(2022, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 1360.9200000000001
                        },
                        new
                        {
                            InvoiceNo = "000591",
                            CusCode = 893623,
                            IssueDate = new DateTime(2022, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 6451.25
                        },
                        new
                        {
                            InvoiceNo = "000592",
                            CusCode = 893623,
                            IssueDate = new DateTime(2022, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalValue = 2989.9499999999998
                        });
                });

            modelBuilder.Entity("DataHandler.DataAccess.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("DataHandler.DataAccess.CustomerInvoice", b =>
                {
                    b.HasOne("DataHandler.DataAccess.Customer", "Customer")
                        .WithMany("CustomerInvoices")
                        .HasForeignKey("CusCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DataHandler.DataAccess.Customer", b =>
                {
                    b.Navigation("CustomerInvoices");
                });
#pragma warning restore 612, 618
        }
    }
}
